language: python
python: "3.6"
dist: xenial

stages:
  - test

cache: pip

jobs:
  include:
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - pytest --cov
