site_name: quaternionic

repo_url: https://github.com/moble/quaternionic

plugins:
  - mktheapidocs:
      modules: 
        quaternionic:
          section: api 
          source_repo: "https://github.com/moble/quaternionic"

theme:
  name: 'readthedocs'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
